const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  // ─── Categories ───────────────────────────────────────────────────────────
  const [food, activity, attraction, nightlife, shopping, nature] = await Promise.all([
    prisma.category.upsert({ where: { slug: 'food' },       update: {}, create: { name: 'Food',       slug: 'food',       icon: '🍽️' } }),
    prisma.category.upsert({ where: { slug: 'activity' },   update: {}, create: { name: 'Activity',   slug: 'activity',   icon: '🎯' } }),
    prisma.category.upsert({ where: { slug: 'attraction' }, update: {}, create: { name: 'Attraction', slug: 'attraction', icon: '🏛️' } }),
    prisma.category.upsert({ where: { slug: 'nightlife' },  update: {}, create: { name: 'Nightlife',  slug: 'nightlife',  icon: '🎶' } }),
    prisma.category.upsert({ where: { slug: 'shopping' },   update: {}, create: { name: 'Shopping',   slug: 'shopping',   icon: '🛍️' } }),
    prisma.category.upsert({ where: { slug: 'nature' },     update: {}, create: { name: 'Nature',     slug: 'nature',     icon: '🌿' } }),
  ]);

  const cat = { food, activity, attraction, nightlife, shopping, nature };

  async function assignCategories(placeId, cats) {
    for (const c of cats) {
      await prisma.placeCategory.upsert({
        where: { placeId_categoryId: { placeId, categoryId: c.id } },
        update: {},
        create: { placeId, categoryId: c.id },
      });
    }
  }

  // ─── Destinations (92) ────────────────────────────────────────────────────
  const destinationData = [
    { name: 'New York',        country: 'United States',   slug: 'new-york',          description: 'New York City is the cultural and financial capital of the world, a place where ambition and creativity collide across five boroughs. From the High Line and Central Park to the neon pulse of Times Square, every neighbourhood tells a different story. Travellers come for world-class museums like the Met and MoMA, legendary pizza and bagels, Broadway shows, and the electric energy that makes every visit feel cinematic.' },
    { name: 'Tokyo',           country: 'Japan',           slug: 'tokyo',             description: 'Tokyo is one of the most captivating cities on earth — a seamless blend of ancient Shinto shrines and dazzling neon technology that somehow feels perfectly balanced. It is the world\'s largest metropolitan area, yet it runs with extraordinary precision and courtesy. Visitors fall in love with the incredible diversity of food (from Michelin-starred omakase to 500-yen ramen), the obsessive craftsmanship found in every craft and shop, and the way centuries-old neighbourhoods like Yanaka sit quietly next to hypermodern districts like Shibuya.' },
    { name: 'Paris',           country: 'France',          slug: 'paris',             description: 'Paris is the benchmark against which all other cities are measured — a living monument to art, architecture, cuisine, and romance that has drawn dreamers for centuries. Walking its grand boulevards and hidden passages, you encounter the Eiffel Tower, the Louvre, and Notre-Dame, but also intimate wine bars, flower markets, and bakeries perfecting the croissant. The French capital rewards slow travel: the longer you stay, the more you understand why artists, writers, and lovers have always chosen to call it home.' },
    { name: 'Mexico City',     country: 'Mexico',          slug: 'mexico-city',       description: 'Mexico City is one of the great metropolises of the Americas — a 3,000-year-old cultural powerhouse sitting at 2,240 metres above sea level. Built on the ruins of the Aztec capital Tenochtitlán, the city layers pre-Hispanic pyramids, colonial cathedrals, and modernist murals by Diego Rivera into a dense, exhilarating urban canvas. Its food scene is among the world\'s best, from tacos al pastor eaten at midnight street stalls to avant-garde tasting menus in Polanco, and its art, music, and neighbourhood culture make it endlessly rewarding to explore.' },
    { name: 'London',          country: 'United Kingdom',  slug: 'london',            description: 'London is one of the world\'s great cities — a place that has reinvented itself across two millennia while never losing its sense of history and ceremony. You can walk from the Tower of London to Tate Modern in under an hour, passing pubs, market stalls, and world-class architecture along the way. What makes London special is its diversity: it is simultaneously a royal capital, a global financial centre, a street food paradise, and a hub of music and fashion that consistently shapes global culture.' },
    { name: 'Barcelona',       country: 'Spain',           slug: 'barcelona',         description: 'Barcelona is Europe\'s most architecturally audacious city, shaped above all by Antoni Gaudí, whose organic, otherworldly buildings — the Sagrada Família, Park Güell, Casa Batlló — feel like no other structures on earth. Beyond the architecture, the city delivers on every front: golden Mediterranean beaches just minutes from the Gothic Quarter\'s medieval lanes, the legendary food market La Boqueria, and a culinary scene anchored by tapas, seafood, and Catalan cuisine. The city\'s passion for football, festivals, and late-night dining gives it a vibrancy that keeps visitors coming back.' },
    { name: 'Rome',            country: 'Italy',           slug: 'rome',              description: 'Rome is the Eternal City for good reason — nowhere else on earth can you wander from a 2,000-year-old amphitheatre to a Renaissance piazza to a Baroque fountain in a single afternoon stroll. The layers of history are staggering: ancient forums, early Christian catacombs, Vatican masterpieces, and the café culture of a living, breathing modern capital all occupy the same streets. Romans eat extraordinarily well — cacio e pepe, supplì, gelato — and the combination of beauty, history, and food makes Rome one of the most deeply satisfying cities to visit.' },
    { name: 'Bangkok',         country: 'Thailand',        slug: 'bangkok',           description: 'Bangkok is one of Southeast Asia\'s most thrilling cities — a chaotic, beautiful, and endlessly surprising place where golden temples rise above street-food-lined canals and rooftop bars overlook a glittering skyline. The Grand Palace and Wat Pho anchor a sacred historic core, while neighbourhoods like Chinatown and Ari buzz with energy day and night. Bangkok\'s street food scene is among the world\'s best, and the city\'s reputation for legendary nightlife, world-class spas, and extraordinary value make it one of the most visited destinations on the planet.' },
    { name: 'Sydney',          country: 'Australia',       slug: 'sydney',            description: 'Sydney is blessed with one of the most spectacular natural settings of any city in the world — a dazzling harbour framed by the iconic Opera House and Harbour Bridge, surrounded by ocean beaches and national park bushland. The city is relaxed and outdoors-oriented in a way that feels effortless: morning swims at Bondi, afternoon ferry rides to Manly, evenings in Surry Hills wine bars. Australia\'s largest city also punches well above its weight culturally, with world-class galleries, a diverse food scene shaped by its multicultural population, and a warmth that makes visitors feel immediately at home.' },
    { name: 'Cape Town',       country: 'South Africa',    slug: 'cape-town',         description: 'Cape Town is arguably Africa\'s most spectacular city, pinned between the flat-topped drama of Table Mountain and the cold Atlantic Ocean in a setting of almost absurd natural beauty. The city delivers an exceptional range of experiences: wine tasting in the Winelands valleys of Stellenbosch and Franschhoek, penguin encounters at Boulders Beach, dramatic drives along Chapman\'s Peak, and a vibrant food and arts scene centred on the Victoria & Alfred Waterfront. Its complex history — and the ongoing story of a society remaking itself — gives Cape Town a depth and emotional resonance that goes far beyond its postcard-perfect views.' },
    { name: 'Dubai',           country: 'UAE',             slug: 'dubai',             description: 'Dubai is the world\'s most audacious urban experiment — a desert city that has transformed itself in a single generation into a global hub of commerce, luxury, and spectacle. The Burj Khalifa soars above a skyline of record-breaking towers, while the Palm Jumeirah stretches into the Gulf as a feat of human engineering. Beyond the glamour, Dubai rewards deeper exploration: the gold and spice souks of Deira, the wind-tower architecture of Al Fahidi, and the warm hospitality of Emirati culture offer a more nuanced picture of a city that is far more than just superlatives.' },
    { name: 'Istanbul',        country: 'Turkey',          slug: 'istanbul',          description: 'Istanbul is the only city in the world that straddles two continents, and its position at the crossroads of Europe and Asia has made it one of history\'s great meeting points of civilisation. The skyline is defined by the minarets of the Blue Mosque and the dome of Hagia Sophia — a building that has served as cathedral, mosque, and museum over its 1,500-year history. Visitors are drawn by the Grand Bazaar\'s labyrinthine lanes, the fresh fish sandwiches sold on the Galata Bridge, the melancholy beauty of a Bosphorus sunset, and a food culture — from mezze to baklava — that is among the richest in the world.' },
    { name: 'Amsterdam',       country: 'Netherlands',     slug: 'amsterdam',         description: 'Amsterdam is one of Europe\'s most liveable and loveable cities — a compact, canal-laced masterpiece built on merchant ambition in the 17th century\'s Golden Age. The ring of concentric canals lined with leaning gabled townhouses is a UNESCO World Heritage Site, best explored by bicycle or boat. The city punches far above its size culturally: the Rijksmuseum houses Rembrandt and Vermeer, the Van Gogh Museum is unmissable, and the Anne Frank House offers one of the most moving experiences in Europe. Amsterdam\'s tolerance, café culture, and extraordinary density of art and history make it deeply rewarding at any pace.' },
    { name: 'Singapore',       country: 'Singapore',       slug: 'singapore',         description: 'Singapore is one of the world\'s great city-states — a tiny island nation that has built itself into a global powerhouse of finance, design, and gastronomy through sheer ambition and meticulous planning. The Gardens by the Bay\'s Supertrees and the infinity pool of Marina Bay Sands have become defining images of 21st-century urbanism. But Singapore\'s real heart is in its food: the hawker centre culture, where Michelin-starred chicken rice and char kway teow are served on plastic trays for a few dollars, is a national obsession and a genuine source of civic pride.' },
    { name: 'Prague',          country: 'Czech Republic',  slug: 'prague',            description: 'Prague is one of Europe\'s best-preserved medieval cities — a fairy-tale skyline of Gothic spires, Baroque domes, and Art Nouveau façades that miraculously escaped serious damage in the Second World War. The Old Town Square, Charles Bridge at dawn, and the castle district looming above the Vltava River create an atmosphere of almost theatrical romance. Prague\'s legendary beer culture — Bohemia is the birthplace of Pilsner — means the city also knows how to have a good time, and its combination of architectural splendour, affordability, and central European charm makes it one of the most visited cities on the continent.' },
    { name: 'Buenos Aires',    country: 'Argentina',       slug: 'buenos-aires',      description: 'Buenos Aires is South America\'s most European city — a sprawling, passionate capital built by Italian and Spanish immigrants who brought their architecture, café culture, and love of football to the banks of the Río de la Plata. The city\'s neighbourhoods each have a distinct personality: the colourful Caminito street art of La Boca, the grand Parisian boulevards of Recoleta, the antique markets and tango bars of San Telmo. Argentine beef is world-famous for good reason, and a Buenos Aires parilla dinner followed by a late-night milonga is one of travel\'s great experiences.' },
    { name: 'Bali',            country: 'Indonesia',       slug: 'bali',              description: 'Bali is the world\'s most beloved tropical island destination — a place of extraordinary natural beauty and spiritual richness that captivates every kind of traveller. Emerald rice terraces cascade down volcanic slopes, temple ceremonies fill the air with incense and gamelan music, and world-class surf breaks the waves of Uluwatu and Canggu. What sets Bali apart from other island paradises is the depth of its Hindu culture: daily flower offerings, elaborate cremation ceremonies, and a philosophy of balance called Tri Hita Karana give the island a soul that goes far beyond its famous sunsets and luxury villas.' },
    { name: 'Marrakech',       country: 'Morocco',         slug: 'marrakech',         description: 'Marrakech is a full sensory assault in the best possible way — a medieval medina of labyrinthine souks, the smell of cumin and rose water, the sound of Gnawa musicians, and the sight of snake charmers and acrobats in the vast Djemaa el-Fna square. The city\'s riads — traditional courtyard houses converted into boutique guesthouses — offer an extraordinary contrast to the chaos outside: cool tiles, orange trees, and rooftop terraces overlooking a sea of minarets. Morocco\'s red city rewards those who get lost in its alleys, bargain for leather goods in the tanneries, and stay long enough to appreciate its layers.' },
    { name: 'Kyoto',           country: 'Japan',           slug: 'kyoto',             description: 'Kyoto is Japan\'s cultural heart — the country\'s imperial capital for over a thousand years and home to more than 1,600 Buddhist temples and 400 Shinto shrines. The Arashiyama bamboo grove, the thousands of vermillion torii gates of Fushimi Inari, and the gold-leafed Kinkaku-ji pavilion reflected in still water are images that define Japan for many travellers. Kyoto is also the place to encounter geiko and maiko in the Gion district, participate in a traditional tea ceremony, and eat kaiseki — the refined, multi-course cuisine that is Japan\'s highest culinary art form.' },
    { name: 'Rio de Janeiro',  country: 'Brazil',          slug: 'rio-de-janeiro',    description: 'Rio de Janeiro is one of the world\'s most dramatically beautiful cities — a place where jungle-covered mountains plunge straight into the Atlantic, creating a coastline of impossibly scenic beaches watched over by the outstretched arms of Christ the Redeemer. The city lives for Carnival, a five-day explosion of samba, colour, and joy that is the greatest street party on earth. But Rio rewards year-round visits: hang-gliding over Ipanema, riding the cable car to Sugarloaf Mountain at sunset, and eating churrasco in a neighbourhood boteco all capture the carioca spirit of pleasure, beauty, and warmth.' },
    { name: 'Lisbon',          country: 'Portugal',        slug: 'lisbon',            description: 'Lisbon is one of Europe\'s oldest and most romantic capitals — a city of seven hills draped in azulejo tiles, where yellow trams rattle through narrow lanes and the melancholy music of fado drifts from tavern doorways. It was the launchpad of the Age of Discovery, and the ornate Manueline architecture of the Jerónimos Monastery stands as a monument to that era of global exploration. Today, Lisbon has reinvented itself as one of Europe\'s most exciting destinations for food, wine, and culture, with the time-glo neighbourhood of LX Factory and a pastel de nata in every café window.' },
    { name: 'Vienna',          country: 'Austria',         slug: 'vienna',            description: 'Vienna is the imperial city par excellence — a place where the grandeur of the Habsburg Empire lives on in its palaces, opera houses, and coffee houses in a way that feels entirely natural rather than preserved. The Kunsthistorisches Museum, the Belvedere, and the Albertina hold some of the world\'s greatest art collections, while the Vienna State Opera and the concert halls of the Musikverein make it the undisputed capital of classical music. Vienna\'s café culture — lingering over a Melange and a slice of Sachertorte for hours — is a UNESCO Intangible Cultural Heritage and one of the great pleasures of European travel.' },
    { name: 'Seoul',           country: 'South Korea',     slug: 'seoul',             description: 'Seoul is one of the world\'s most dynamic and forward-looking cities — a place that has gone from wartime devastation to global cultural powerhouse in just two generations. Ancient palaces like Gyeongbokgung stand in the shadow of glass skyscrapers, while the Han River bisects a city that never seems to sleep. Korean cuisine — barbecue, bibimbap, kimchi, and the fiery stews of the pojangmacha food tents — is having a global moment, and Seoul is the best place to understand why. Add the global influence of K-pop and K-drama, the beauty rituals of Myeongdong, and the cutting-edge fashion of Hongdae, and you have one of Asia\'s most exciting destinations.' },
    { name: 'Havana',          country: 'Cuba',            slug: 'havana',            description: 'Havana is unlike any other city on earth — a time-capsule capital of crumbling colonial grandeur, 1950s American automobiles in candy colours, and a people of extraordinary warmth and musical talent. The Malecón seawall, where Habaneros gather at sunset to drink rum and play guitar, is one of the world\'s great public spaces. Cuba\'s isolation has preserved Havana\'s architectural beauty and given its culture an authenticity that is increasingly rare, and while the city faces real challenges, its energy, its music — son, rumba, jazz — and its fierce sense of identity make it one of the most memorable places a traveller can visit.' },
    { name: 'New Orleans',     country: 'United States',   slug: 'new-orleans',       description: 'New Orleans is America\'s most unique city — a place shaped equally by French, Spanish, African, and Caribbean influences into something that feels like nowhere else in the United States. The French Quarter\'s wrought-iron balconies, the live jazz pouring from Frenchmen Street bars, and the annual Mardi Gras celebrations are famous worldwide, but the city\'s greatest gift may be its food: gumbo, jambalaya, beignets, po\'boys, and the profound complexity of Creole and Cajun cuisine. New Orleans has a soulfulness — born partly of suffering, partly of joy — that touches every visitor deeply.' },
    { name: 'Edinburgh',       country: 'United Kingdom',  slug: 'edinburgh',         description: 'Edinburgh is one of Europe\'s most dramatically beautiful capitals, built around an ancient volcanic crag topped by a brooding castle that has dominated the Scottish skyline for centuries. The medieval Royal Mile connects the castle to the Palace of Holyroodhouse through a dense layer of history, wynds, and taverns, while the neoclassical New Town offers a completely different architectural grandeur. Every August, the city transforms into the world\'s largest arts festival, but Edinburgh rewards visits year-round with its whisky bars, Arthur\'s Seat hikes, the National Museum of Scotland, and a dry wit and warmth unique to its people.' },
    { name: 'San Francisco',   country: 'United States',   slug: 'san-francisco',     description: 'San Francisco is one of America\'s most beautiful and eccentric cities — a compact peninsula of Victorian painted ladies, fog-wreathed hills, and the rust-red span of the Golden Gate Bridge arching across a magnificent bay. The city has always been a place of reinvention and counterculture, from the Gold Rush to the Beat Generation to the Summer of Love to the tech revolution, and that spirit of restless creativity still permeates its neighbourhoods. The Ferry Building farmers\' market, the Mission\'s burritos, Chinatown\'s dim sum, and the sourdough of Fisherman\'s Wharf give the city a food scene as layered as its topography.' },
    { name: 'Nairobi',         country: 'Kenya',           slug: 'nairobi',           description: 'Nairobi is East Africa\'s most vibrant and cosmopolitan capital — the only city in the world with a national park on its doorstep, where lions roam against a backdrop of downtown skyscrapers. It is the primary gateway to Kenya\'s world-famous safari circuits: the Masai Mara, Amboseli, and Tsavo are all within reach. But Nairobi itself rewards exploration: the Westlands dining scene, the Maasai Market crafts, the Karen Blixen Museum, and a startup and arts culture that has made the city a hub of African innovation and creativity.' },
    { name: 'Mumbai',          country: 'India',           slug: 'mumbai',            description: 'Mumbai is India\'s city of dreams — a teeming, relentless, magnificent metropolis of 20 million people where the country\'s richest and poorest live within walking distance of each other. The Gothic and Art Deco architecture of the city centre, the Gateway of India overlooking the Arabian Sea, and the Dabbawalas\' legendary lunch-delivery network are iconic Mumbai. But the city is best understood through its street food — vada pav, pav bhaji, bhel puri at Chowpatty Beach — its Bollywood energy, and the extraordinary resilience and hospitality of its people.' },
    { name: 'Athens',          country: 'Greece',          slug: 'athens',            description: 'Athens is the cradle of Western civilisation — the city where democracy, philosophy, and theatre were born, and where the Parthenon has watched over an unbroken 3,500 years of human habitation from its hilltop perch above the city. The Acropolis Museum houses the finest collection of classical Greek sculpture in the world, and the ancient agora where Socrates argued still echoes with a sense of the past. Modern Athens surprises many visitors: the street art of Psyrri, the rooftop bars of Monastiraki, the fresh seafood of Piraeus, and a café culture to rival any in Europe make it one of Europe\'s most underrated capitals.' },
    { name: 'Copenhagen',      country: 'Denmark',         slug: 'copenhagen',        description: 'Copenhagen is consistently rated the world\'s most liveable city, and a visit reveals exactly why: it is beautiful, functional, sustainable, and deeply civilised in a way that feels both aspirational and completely real. The coloured facades of Nyhavn, the spires of Christiansborg, and the cycling infrastructure that moves most of the city without a car are defining images. But Copenhagen is perhaps most famous today for food: Noma sparked a global revolution in Nordic cuisine, and the city now hosts a concentration of world-class restaurants that is extraordinary for its size, alongside the open-faced smørrebrød and pastries of its bakery culture.' },
    { name: 'Cartagena',       country: 'Colombia',        slug: 'cartagena',         description: 'Cartagena is one of the best-preserved colonial cities in the Americas — a walled Caribbean port whose pastel-coloured streets, flower-draped balconies, and 16th-century fortifications create a setting of extraordinary romance. The Castillo San Felipe de Barajas is one of the greatest Spanish fortifications in the New World, built to defend the city\'s status as the primary port for New World gold flowing back to Spain. Beyond the old town walls, the beaches of the Rosario Islands and the Afro-Caribbean culture of Palenque — the first free African town in the Americas — add layers of history and beauty to what is already one of South America\'s most captivating destinations.' },
    { name: 'Ho Chi Minh City',country: 'Vietnam',         slug: 'ho-chi-minh-city',  description: 'Ho Chi Minh City — still widely called Saigon — is Vietnam\'s most kinetic and commercially driven metropolis, a city that has transformed itself from wartime devastation into one of Southeast Asia\'s fastest-growing economies with remarkable speed and energy. The streets pulse with millions of motorbikes weaving between French colonial buildings, modern skyscrapers, and street food carts serving the world\'s best banh mi and pho. The War Remnants Museum provides an essential and sober counterpoint, while the Mekong Delta day trips, the Cu Chi tunnels, and the extraordinary food scene of Bui Vien street make the city endlessly fascinating.' },
    { name: 'Seville',         country: 'Spain',           slug: 'seville',           description: 'Seville is the soul of Andalusia — a sun-drenched city of flamenco, orange trees, and extraordinary Islamic and Christian architecture that represents the most romantic face of Spain. The Alcázar palace, with its intricate Mudéjar tilework and immaculate gardens, is one of the most beautiful buildings in Europe, and the Gothic cathedral — the world\'s largest — houses the tomb of Christopher Columbus. Seville comes alive during Semana Santa, when elaborate religious processions fill the streets for Holy Week, and during the April Feria, when the city erupts into a week of dancing, horses, and sherry that is unlike anything else in Europe.' },
    { name: 'Cairo',           country: 'Egypt',           slug: 'cairo',             description: 'Cairo is one of the world\'s great ancient cities — a sprawling, chaotic, intoxicating metropolis on the Nile that serves as the gateway to one of humanity\'s most extraordinary civilisations. The Pyramids of Giza and the Sphinx, rising from the desert on the city\'s western edge, remain among the most awe-inspiring structures ever built by human hands. The Egyptian Museum holds the treasures of Tutankhamun, the Khan el-Khalili bazaar has been trading since the 14th century, and the Islamic architecture of Old Cairo — its mosques, minarets, and medieval madrassas — rivals anything in the Muslim world.' },
    { name: 'Berlin',          country: 'Germany',         slug: 'berlin',            description: 'Berlin is one of the most fascinating capitals in the world — a city that has lived through more history than almost any other in the 20th century and has emerged with a raw, creative energy unlike anywhere else in Europe. The remnants of the Berlin Wall, Checkpoint Charlie, the Holocaust Memorial, and the East Side Gallery are reminders of a divided past that still shapes the city\'s identity. Berlin\'s celebrated club culture — rooted in the abandoned factories and bunkers of the former East — is the world\'s most influential, but the city is also home to world-class museums on Museum Island, a thriving street food scene, and some of Europe\'s most affordable and creative neighbourhoods.' },
    { name: 'Dubrovnik',       country: 'Croatia',         slug: 'dubrovnik',         description: 'Dubrovnik is one of the most perfectly preserved medieval cities in the world — a walled city-state on the Adriatic whose limestone streets, Baroque fountains, and terracotta rooftops within mighty 13th-century walls create an atmosphere of timeless Mediterranean beauty. Walking the 2km circuit of the city walls, with the dazzling blue Adriatic on one side and the red-roofed old town on the other, is one of Europe\'s great experiences. Known to millions as the filming location for King\'s Landing in Game of Thrones, Dubrovnik is also a gateway to the Dalmatian islands of Hvar, Brač, and Korčula, making it the perfect base for Croatian island-hopping.' },
    { name: 'Medellin',        country: 'Colombia',        slug: 'medellin',          description: 'Medellín\'s transformation is one of the great urban stories of the 21st century — a city once synonymous with violence that has reinvented itself through cable cars, escalators, libraries, and community investment into one of Latin America\'s most innovative and liveable cities. Nestled in a green Andean valley with spring-like temperatures year-round, the City of Eternal Spring combines Colombian warmth and paisa hospitality with a creative energy that pulses through its street art, design culture, and nightlife. The Metrocable connecting hillside comunas to the city centre, the flower festival of the Feria de las Flores, and the vibrant El Poblado neighbourhood make it one of South America\'s most compelling destinations.' },
    { name: 'Chiang Mai',      country: 'Thailand',        slug: 'chiang-mai',        description: 'Chiang Mai is the cultural capital of northern Thailand — a relaxed, beautiful city surrounded by mist-covered mountains, dotted with over 300 ancient Lanna temples, and famous for the best food in a country already blessed with extraordinary cuisine. The Old City moat frames a walkable historic core of gilded wats and teak buildings, while the Sunday Night Market and Night Bazaar offer some of Thailand\'s best artisan shopping. Beyond the city, elephant sanctuaries in the jungle, hill tribe village treks, zip-lining through forest canopies, and the surreal floating lanterns of the Yi Peng festival make Chiang Mai one of Southeast Asia\'s most rewarding destinations.' },
    { name: 'Reykjavik',       country: 'Iceland',         slug: 'reykjavik',         description: 'Reykjavik is the world\'s northernmost capital and the gateway to one of earth\'s most spectacular natural environments — a land of geysers, glaciers, volcanoes, and the ethereal Northern Lights that dance above the city in winter. Iceland\'s small size and sparse population have preserved landscapes of raw, elemental beauty: the Golden Circle geysers, the black sand beaches of Vík, the ice caves of Vatnajökull, and the geothermal Blue Lagoon are all within easy reach. Despite its remote setting, Reykjavik has punched well above its weight culturally, with a world-class music scene, innovative Nordic cuisine, and a design sensibility shaped by long dark winters and extraordinary light.' },
    { name: 'Hanoi',           country: 'Vietnam',         slug: 'hanoi',             description: 'Hanoi is Vietnam\'s ancient and atmospheric capital — a city of 1,000 years of history that wears its past in French colonial boulevards, pagoda-dotted Hoan Kiem Lake, and the narrow tube houses of the 36-street Old Quarter that was Vietnam\'s first commercial centre. The city moves at a gentler pace than Ho Chi Minh City, with a northern Vietnamese sensibility that values tradition, refinement, and the ritual of a slow morning pho or egg coffee in a pavement café. The street food of Hanoi is among Asia\'s finest, and nearby Halong Bay — where thousands of limestone karsts rise from emerald water — is one of the world\'s most stunning natural landscapes.' },
    { name: 'Toronto',         country: 'Canada',          slug: 'toronto',           description: 'Toronto is one of the world\'s most genuinely multicultural cities — a Canadian metropolis where over half the population was born outside the country, and where Chinatown, Little Italy, Little India, Greektown, and Koreatown each offer a vivid slice of their homelands within a single city. The CN Tower, the Royal Ontario Museum, and the Art Gallery of Ontario anchor a strong cultural offering, while the revitalised waterfront and the Victorian-era Distillery District have given the city new gathering places. Toronto\'s food scene directly reflects its diversity: it is one of the best cities in the world to eat dim sum, Korean barbecue, Jamaican patties, and West African egusi soup, often within a few blocks of each other.' },
    { name: 'Santorini',       country: 'Greece',          slug: 'santorini',         description: 'Santorini is one of the world\'s most iconic and photographed destinations — a crescent of volcanic cliffs rising from the Aegean Sea, topped by the whitewashed villages of Oia and Fira with their impossibly blue-domed churches and infinity pools overlooking the submerged caldera. The island was shaped by one of history\'s most catastrophic volcanic eruptions, which may have been the origin of the Atlantis myth, and the dramatic landscape of black sand beaches, blood-red cliffs, and turquoise water is unlike anywhere else in the Mediterranean. Santorini\'s wines — particularly the mineral Assyrtiko grape grown in volcanic soil — and its sunset rituals draw visitors from every corner of the world.' },
    { name: 'Florence',        country: 'Italy',           slug: 'florence',          description: 'Florence is the cradle of the Renaissance — a compact, walkable city on the Arno that contains perhaps the highest concentration of great art and architecture in the world. The Uffizi Gallery houses Botticelli\'s Birth of Venus and dozens of other masterpieces; Michelangelo\'s David stands in the Accademia; the Duomo\'s terracotta-tiled dome, engineered by Brunelleschi, was the architectural marvel of the 15th century. But Florence is not merely a museum: the Oltrarno neighbourhood is full of artisan workshops and neighbourhood restaurants, the Mercato Centrale is a paradise of Tuscan produce, and the hills of Fiesole above the city offer views over a landscape that inspired Leonardo da Vinci.' },
    { name: 'Vancouver',       country: 'Canada',          slug: 'vancouver',         description: 'Vancouver is consistently ranked among the world\'s most liveable cities, and it earns that distinction through a combination of natural beauty, outdoor lifestyle, and cosmopolitan culture that is hard to match. Snow-capped mountains rise directly behind the downtown skyline, Stanley Park\'s ancient rainforest meets the Pacific Ocean, and world-class ski slopes at Whistler are just 90 minutes away. Vancouver\'s large Asian-Canadian community has shaped one of North America\'s most exciting food scenes, with exceptional Japanese, Chinese, Korean, and Vietnamese restaurants alongside Pacific Northwest seafood that benefits from some of the world\'s richest waters.' },
    { name: 'Casablanca',      country: 'Morocco',         slug: 'casablanca',        description: 'Casablanca is Morocco\'s largest city and economic powerhouse — a sprawling, modern Atlantic port city that is the country\'s commercial heart rather than its most overtly touristic destination. The Hassan II Mosque is one of the largest and most spectacular mosques in the world, built dramatically on a promontory over the Atlantic with a retractable roof and a minaret that lasers a beam toward Mecca. The Art Deco architecture of the Mauresque style — a blend of French and Moroccan Islamic design — fills the city centre with handsome buildings, and the corniche seafood restaurants and the genuine pace of a working Moroccan city give Casablanca an authenticity that contrasts with the more tourist-trodden medinas to the south.' },
    { name: 'Hong Kong',       country: 'China',           slug: 'hong-kong',         description: 'Hong Kong is one of the world\'s most exhilarating cities — a vertical, intense, brilliantly efficient metropolis built on steep hillsides around one of Asia\'s great natural harbours. The skyline, viewed from the Peak or from the Kowloon waterfront at night, is among the world\'s most dramatic, a forest of illuminated towers reflected in Victoria Harbour. Hong Kong\'s food culture is extraordinary: dim sum is an art form here, the dai pai dong street food stalls are irreplaceable institutions, and the city\'s density of Michelin-starred restaurants rivals any city on earth. The tram rides, the outlying islands, the night markets, and the unique blend of British colonial legacy with vibrant Cantonese culture make it utterly distinctive.' },
    { name: 'Bogotá',          country: 'Colombia',        slug: 'bogota',            description: 'Bogotá is one of South America\'s most underrated capitals — a high-altitude city of 8 million people at 2,600 metres above sea level that has transformed from dangerous neglect into a thriving cultural and culinary powerhouse. The La Candelaria historic district is full of colonial architecture, street art, and the world-class Gold Museum, which holds the largest collection of pre-Hispanic gold in the world. On Sundays, the city shuts its main roads to cars and opens them to cyclists and pedestrians in the Ciclovía — one of the world\'s greatest urban public events — while the restaurants of Zona Rosa and Usaquén represent some of the best dining in Latin America.' },
    { name: 'Stockholm',       country: 'Sweden',          slug: 'stockholm',         description: 'Stockholm is one of Europe\'s most elegant and environmentally conscious capitals — a city of 14 islands connected by bridges, where the medieval streets of Gamla Stan meet the hipster boutiques of Södermalm and the waterways of the archipelago stretch out to the Baltic Sea. The Vasa Museum, which houses a perfectly preserved 17th-century warship raised from the harbour floor, is one of Scandinavia\'s most remarkable attractions, and the ABBA Museum delights visitors of every generation. Stockholm\'s restaurant scene has been transformed in recent decades into one of Europe\'s most exciting, with New Nordic cuisine and a fika culture of coffee and cardamom buns that is a cornerstone of Swedish daily life.' },
    { name: 'Kuala Lumpur',    country: 'Malaysia',        slug: 'kuala-lumpur',      description: 'Kuala Lumpur is Southeast Asia\'s most under-appreciated capital — a vibrant, multicultural city where Malay, Chinese, and Indian cultures have woven together into a unique urban fabric of gleaming towers, street temples, colonial buildings, and some of Asia\'s finest street food. The Petronas Twin Towers, once the world\'s tallest buildings, remain one of the great architectural statements of the late 20th century, and the view from the observation bridge is extraordinary. KL\'s hawker food scene is legendary: nasi lemak, char kway teow, roti canai, and cendol are eaten at all hours in a city that genuinely never stops eating.' },
    { name: 'Oaxaca',          country: 'Mexico',          slug: 'oaxaca',            description: 'Oaxaca is Mexico\'s most culinarily and culturally rich destination — a small colonial city in the southern highlands that has become one of the world\'s great food cities while preserving one of the country\'s most vibrant indigenous cultures. The seven moles, the tlayudas, the grasshopper tacos, and the mezcal produced in surrounding villages are essential eating, and Oaxaca\'s mercados are among the most atmospheric in Latin America. The city also hosts the most elaborate Day of the Dead celebrations in Mexico, and the surrounding valleys are dotted with Zapotec and Mixtec archaeological sites, making it one of the most rewarding destinations in the entire country.' },
    { name: 'Porto',           country: 'Portugal',        slug: 'porto',             description: 'Porto is one of Europe\'s most beautiful and characterful second cities — a working port on the Douro River whose medieval Ribeira quarter, azulejo-tiled churches, and iron-and-glass market halls earned it UNESCO World Heritage status. The city is the birthplace of port wine, and the lodges of Vila Nova de Gaia across the river offer tastings in barrel-lined cellars where the fortified wine has been aged for decades. Porto rewards wandering: the bookshop Livraria Lello is one of the world\'s most beautiful, the Foz beaches are magnificent, and the bacalhau (salt cod) dishes of the local tascas are the most satisfying food in the country.' },
    { name: 'Lagos',           country: 'Nigeria',         slug: 'lagos',             description: 'Lagos is Africa\'s largest city and one of the world\'s most dynamic urban environments — a teeming, ambitious, creative megalopolis of 15 million people that is the undisputed capital of African pop culture. Afrobeats, Nollywood, fashion, and tech all emanate from Lagos with a force that is reshaping the continent and influencing the world. The beaches of Victoria Island, the bar and restaurant scene of Lekki, the art galleries of Ikoyi, and the food — suya, jollof rice, pepper soup — in the city\'s chop bars and upscale restaurants reflect a city of extraordinary vitality, even as it wrestles with the challenges of rapid growth.' },
    { name: 'Montreal',        country: 'Canada',          slug: 'montreal',          description: 'Montreal is Canada\'s most culturally vibrant city — a bilingual, bicultural metropolis with a European sensibility that sets it apart from other North American cities. The underground city, the jazz festival that takes over downtown in summer, the Just for Laughs comedy festival, and the Formula 1 Grand Prix all reflect a city that takes its festivals seriously. Montreal\'s food culture is equally distinctive: the bagels of St-Viateur, the smoked meat of Schwartz\'s, the poutine of every chip truck, and the internationally celebrated restaurants of Mile Ex and the Plateau make it one of the best eating cities on the continent.' },
    { name: 'Zurich',          country: 'Switzerland',     slug: 'zurich',            description: 'Zurich is consistently ranked as the city with the world\'s highest quality of life, and a visit makes it immediately clear why: it is clean, efficient, beautiful, and blessed with a setting on a glacier-fed lake with the Alps visible on the horizon. The medieval Altstadt, the Kunsthaus art museum, and the luxury shopping of Bahnhofstrasse represent Switzerland at its most refined. But Zurich has a less obvious, more surprising side in the former industrial district of Zürich West, where converted factories house some of Europe\'s most innovative restaurants, galleries, and nightclubs, and in the summer lake swimming culture where locals plunge into crystal-clear water from historic bath houses.' },
    { name: 'Cusco',           country: 'Peru',            slug: 'cusco',             description: 'Cusco was the capital of the Inca Empire — the largest pre-Columbian civilisation in the Americas — and the city\'s historic centre is a layered palimpsest of Inca stonework, Spanish colonial architecture, and vibrant indigenous Quechua culture. The massive stones of Sacsayhuamán and the Sacred Valley temples demonstrate an engineering mastery that still puzzles architects, while the cobbled streets of the Plaza de Armas are surrounded by Baroque churches built on Inca foundations. Cusco is the primary gateway to Machu Picchu, one of the world\'s most spectacular archaeological sites, and the starting point for treks through some of the most breathtaking Andean scenery on earth.' },
    { name: 'Osaka',           country: 'Japan',           slug: 'osaka',             description: 'Osaka is Japan\'s culinary capital and its most extrovert, pleasure-loving city — a place where the local philosophy of kuidaore ("eat until you drop") is a civic virtue and the street food of Dotonbori is among the most exhilarating eating in Asia. Takoyaki octopus balls, okonomiyaki savoury pancakes, kushikatsu skewers, and ramen are consumed with infectious enthusiasm in a city that is warmer and louder than reserved Tokyo. Osaka Castle, Universal Studios Japan, the teamLab digital art installations, and easy day trips to Nara\'s deer parks and Kyoto\'s temples make the city both a destination in its own right and the best base for exploring the Kansai region.' },
    { name: 'Phuket',          country: 'Thailand',        slug: 'phuket',            description: 'Phuket is Thailand\'s largest island and its most developed beach destination — a tropical paradise of turquoise waters, white sand beaches, limestone karst scenery, and a resort infrastructure that ranges from backpacker bungalows to ultra-luxury private villas. Patong, Kata, and Kamala beaches each have distinct characters, while the day trips by longtail boat to the Phi Phi islands and Phang Nga Bay\'s famous James Bond Island scenery are among Southeast Asia\'s most iconic. Phuket Town\'s Sino-Portuguese heritage and the night markets of Rawai offer a glimpse of the island\'s culture beyond the beach, and the seafood — grilled on the beach at sunset — is some of the finest in Thailand.' },
    { name: 'Tallinn',         country: 'Estonia',         slug: 'tallinn',           description: 'Tallinn is one of Northern Europe\'s best-kept secrets — a remarkably intact medieval city whose Gothic town hall, merchant towers, and cobblestone alleys within ancient limestone walls feel like a living fairy tale that somehow survived the Soviet era with its bones intact. The view from Toompea Hill over the old town and out to the Baltic Sea is extraordinary, and the city\'s compactness makes it wonderfully walkable. Estonia is also one of the world\'s most digitally advanced societies — the country that invented Skype and pioneered e-government — and Tallinn\'s startups, design culture, and innovative restaurant scene give the medieval city a very 21st-century spirit.' },
    { name: 'Beirut',          country: 'Lebanon',         slug: 'beirut',            description: 'Beirut is the Middle East\'s most cosmopolitan city — a place of extraordinary resilience that has been rebuilt multiple times and yet retains a spirit of intellectual freedom, cultural vibrancy, and legendary hospitality that is unique in the region. Lebanese cuisine is one of the world\'s great culinary traditions, and Beirut\'s restaurants, from the neighbourhood hummus joints of Hamra to the innovative fine dining of Gemmayzeh, represent it at its finest. The city\'s Corniche promenade, the Roman ruins beneath the downtown, and the nightlife of Mar Mikhael attract visitors who find a city that is beautiful, complicated, proudly European and Arab at once, and impossible to forget.' },
    { name: 'Accra',           country: 'Ghana',           slug: 'accra',             description: 'Accra is West Africa\'s most welcoming capital — the city that launched the "Year of Return" initiative in 2019, inviting the African diaspora home, and which has positioned itself as the cultural and political heart of the continent. Ghana was the first sub-Saharan African country to gain independence, and Accra\'s National Museum, Kwame Nkrumah Memorial Park, and the slave castles of Cape Coast reflect that proud, complex history. The city\'s beach clubs, Afrobeats scene, jollof rice eaten from street stalls, and the extraordinary warmth of its people — Ghanaian hospitality is legendary — make it one of Africa\'s most rewarding travel experiences.' },
    { name: 'Queenstown',      country: 'New Zealand',     slug: 'queenstown',        description: 'Queenstown is the self-proclaimed adventure capital of the world, and it delivers on that title with extraordinary natural drama: a lakeside alpine town ringed by the jagged Remarkables mountain range, where bungee jumping, skydiving, white-water rafting, jet boating, and skiing are available year-round. The town sits on the shores of Lake Wakatipu, whose glacial blue water changes colour with the light in ways that seem almost unreal. Beyond the adrenaline, Queenstown is also a gateway to the Fiordland — Milford Sound and Doubtful Sound are among the world\'s most spectacular natural wonders — and the surrounding Central Otago region produces some of New Zealand\'s finest Pinot Noir.' },
    { name: 'Tbilisi',         country: 'Georgia',         slug: 'tbilisi',           description: 'Tbilisi is one of the world\'s great undiscovered travel destinations — a 1,500-year-old city in the Caucasus Mountains where medieval churches cling to cliffsides, sulfurous hot springs bubble beneath the Old Town, and the natural wine scene is rooted in the world\'s oldest winemaking tradition, dating back 8,000 years. The mix of Persian, Ottoman, Russian, and Georgian influences gives the architecture a beguiling eclecticism, from the carved wooden balconies of the Old Town to the futuristic Rike Park concert hall. Georgian cuisine — khinkali dumplings, khachapuri cheese bread, walnut-rich sauces — is one of the most distinctive and underrated in the world.' },
    { name: 'Valparaíso',      country: 'Chile',           slug: 'valparaiso',        description: 'Valparaíso is Chile\'s most poetic city — a chaotic, colourful port on 42 hills tumbling down to the Pacific, where every surface is covered in extraordinary street art and the ascensores (funicular lifts) connect the bohemian cerros to the flat port district below. Pablo Neruda called it one of the world\'s most beautiful cities, and his house La Sebastiana — one of three museums in his former homes — is a pilgrimage for literature lovers. The city has long been a gathering point for artists, musicians, and anarchists, and its labyrinthine streets, sea views, and the genuine grit and beauty of a working port give it a character unlike anywhere else in Latin America.' },
    { name: 'Tel Aviv',        country: 'Israel',          slug: 'tel-aviv',          description: 'Tel Aviv is the Middle East\'s most surprising city — a young, sun-soaked Mediterranean metropolis built almost entirely in the 20th century that has become a global leader in tech, food, LGBTQ+ culture, and nightlife while managing to maintain the relaxed beach lifestyle of a city that genuinely loves the sea. The White City — the world\'s largest concentration of Bauhaus architecture, a UNESCO World Heritage Site — gives Tel Aviv a distinctive aesthetic, and the Carmel and HaCarmel markets overflow with Israeli produce, spices, and street food. The hummus of Abu Hassan, the beaches of Gordon and Frishman, and the bars of Florentin and Rothschild Boulevard make it one of the most enjoyable cities in the region.' },
    { name: 'Bruges',          country: 'Belgium',         slug: 'bruges',            description: 'Bruges is medieval Europe in amber — a perfectly preserved Flemish trading city whose 13th-century canals, belfries, horse-drawn carriages, and chocolate shops have earned it the nickname the Venice of the North. The city was one of the wealthiest in Europe during the Middle Ages, and its extraordinary collection of Flemish Primitive paintings, including Jan van Eyck\'s works in the Groeningemuseum, reflects that cultural legacy. Bruges is compact enough to explore entirely on foot or by bicycle in a day, and its breweries — Bruges is the heartland of Belgian brewing — offer the perfect excuse to linger over a Trappist beer and a plate of moules-frites as the canals drift by.' },
    { name: 'Kathmandu',       country: 'Nepal',           slug: 'kathmandu',         description: 'Kathmandu is the gateway to the Himalayas and one of Asia\'s most spiritually charged cities — a valley ringed by 8,000-metre peaks where Hindu and Buddhist traditions are inseparably intertwined in an ancient urban landscape of temples, stupas, and sacred courtyards. Swayambhunath\'s all-seeing Buddha eyes watch over the city from a hilltop, Pashupatinath\'s burning ghats on the Bagmati River are among the most moving religious sites in Asia, and the medieval durbar squares of Kathmandu, Patan, and Bhaktapur are extraordinary concentrations of Newari art and architecture. The city is also the logistical hub for Everest Base Camp treks and the Annapurna Circuit — two of the world\'s greatest mountain journeys.' },
    { name: 'Addis Ababa',     country: 'Ethiopia',        slug: 'addis-ababa',       description: 'Addis Ababa is the political capital of Africa — home to the African Union and the UN Economic Commission for Africa — and a city that carries the weight of a 3,000-year-old civilisation with quiet pride. Ethiopia was never colonised by a European power, and that independence is written into the city\'s character, its food, its coffee ceremony, and its relationship to its extraordinary history. The National Museum houses Lucy, the 3.2-million-year-old hominid skeleton that rewrote human history, while the Merkato — Africa\'s largest open-air market — and the injera restaurants of Bole district offer a vivid introduction to Ethiopian culture and cuisine.' },
    { name: 'Chicago',         country: 'United States',   slug: 'chicago',           description: 'Chicago is America\'s great second city — and in many ways, its most complete one: a lakefront metropolis of stunning architecture, world-class museums, a legendary blues and jazz heritage, and a food scene that invented deep-dish pizza and the Chicago hot dog while also developing one of the world\'s most innovative fine dining cultures. The Chicago Architecture Foundation river cruise is one of the best ways to understand how one city became the birthplace of modern architecture, from Louis Sullivan\'s pioneering skyscrapers to the Millennium Park\'s Cloud Gate. The Art Institute, Grant Park, the blues bars of Buddy Guy\'s Legends, and the extraordinary diversity of neighbourhoods from Pilsen to Chinatown give Chicago an energy and depth that rivals any city in the world.' },
    { name: 'Taipei',          country: 'Taiwan',          slug: 'taipei',            description: 'Taipei is one of Asia\'s most underrated cities — a friendly, safe, and exceptionally well-organised capital that combines Chinese cultural heritage, Japanese colonial influences, and a uniquely Taiwanese creativity in food, design, and democratic civic life. The night markets of Shilin, Raohe, and Ningxia are legendary — stinky tofu, oyster vermicelli, scallion pancakes — and the city\'s beef noodle soup is considered by many food writers to be one of the world\'s perfect dishes. Taipei 101 towers above a city that also offers hot spring baths in Beitou, the tea plantations and hiking trails of Maokong, and the National Palace Museum\'s collection of Chinese imperial treasures, making it one of Asia\'s most complete travel experiences.' },
    { name: 'Budapest',        country: 'Hungary',         slug: 'budapest',          description: 'Budapest is one of Europe\'s most romantically beautiful capitals — a city of grand boulevards, Ottoman-era thermal baths, and a Danube panorama so magnificent it has been a UNESCO World Heritage Site since 1987. The Parliament Building, illuminated at night above the river, is arguably the most beautiful neo-Gothic building in the world, and the Castle District\'s Fishermen\'s Bastion looks across to it from the Buda hills. Budapest\'s ruin bar culture — irreverent, creative bars built inside crumbling courtyards and abandoned Jewish Quarter buildings — is one of Europe\'s most original nightlife inventions, and the city\'s thermal bath culture, rooted in Ottoman occupation, gives it a spa tradition unlike anywhere else in Europe.' },
    { name: 'Auckland',        country: 'New Zealand',     slug: 'auckland',          description: 'Auckland is the City of Sails — a sun-drenched harbour city built across a volcanic field of 53 dormant cones on a narrow isthmus between two seas, giving it a geography as dramatic as any city in the Pacific. The Waitematā Harbour, Waitemata Harbour bridge, and the volcanic island of Rangitoto rising from the water define a skyline that is unlike any other. Auckland is the world\'s largest Polynesian city, and the Pacific Island and Māori cultures that shape it give it a warmth and distinctiveness that is entirely its own. Day trips to the Waitākere Ranges, the wine estates of Waiheke Island, and the thermal fields of Rotorua make Auckland the ideal base for exploring New Zealand\'s North Island.' },
    { name: 'Colombo',         country: 'Sri Lanka',       slug: 'colombo',           description: 'Colombo is Sri Lanka\'s vibrant port capital — a tropical city shaped by centuries of Portuguese, Dutch, and British colonialism that has developed a unique cultural character combining Sinhalese, Tamil, Moorish, and European influences in its food, architecture, and daily life. The Pettah market district buzzes with the energy of one of South Asia\'s oldest trading hubs, while the Galle Face Green promenade provides a sea breeze above the Indian Ocean and the Gangaramaya Temple reflects a Buddhism that is central to the island\'s identity. Sri Lanka\'s cinnamon and spice heritage, the coconut-rich curries of the local cuisine, and the proximity to Sigiriya\'s rock fortress, the ancient city of Anuradhapura, and the beaches of the south coast make Colombo an excellent base.' },
    { name: 'Lima',            country: 'Peru',            slug: 'lima',              description: 'Lima has emerged as the gastronomic capital of South America — a Pacific coast city whose extraordinary biodiversity of ingredients, from Amazonian fruits to Andean grains to fresh Pacific ceviche, has given rise to one of the world\'s most exciting food cultures. Central, Maido, and Astrid y Gastón have all been ranked among the world\'s best restaurants, and the neighbourhood of Miraflores overhangs the Pacific on dramatic cliffs above the Miraflores paragliders and surfers below. Lima\'s pre-Columbian ruins — including the Huaca Pucllana pyramid built in the 5th century, surrounded by a modern residential neighbourhood — are a striking reminder of the 3,000-year history beneath the city.' },
    { name: 'Naples',          country: 'Italy',           slug: 'naples',            description: 'Naples is Italy at its most raw, beautiful, chaotic, and alive — a city of extraordinary historical depth, intense flavours, and volcanic drama that has been home to some of the world\'s most important civilisations. The birthplace of pizza, where the Margherita was invented and the wood-fired Neapolitan style remains the global standard, Naples also gave the world limoncello, the mandolin, and the most important opera tradition outside Vienna. The National Archaeological Museum holds the greatest collection of Greco-Roman artefacts in the world, including treasures excavated from Pompeii and Herculaneum — the cities preserved in volcanic ash by Vesuvius in 79 AD, just an hour\'s drive away.' },
    { name: 'Muscat',          country: 'Oman',            slug: 'muscat',            description: 'Muscat is the Gulf\'s most genuinely beautiful and culturally authentic capital — a low-rise, fragrant city of whitewashed buildings, ancient forts, and the extraordinary Sultan Qaboos Grand Mosque spread along a dramatic coastline of mountains meeting the Arabian Sea. Oman has preserved its traditional architecture and culture with rare care: the Muttrah Souq is one of the oldest and most atmospheric markets in the Middle East, and the frankincense trade that made Arabia wealthy for millennia is still celebrated here. Day trips into the Hajar Mountains, the fjords of Musandam, the desert dunes of Wahiba Sands, and the ancient aflaj irrigation systems reveal an Oman of extraordinary natural and historical richness.' },
    { name: 'Phnom Penh',      country: 'Cambodia',        slug: 'phnom-penh',        description: 'Phnom Penh is Cambodia\'s capital and one of Southeast Asia\'s most historically layered cities — a graceful French colonial riverfront metropolis that carries the scars of the Khmer Rouge genocide alongside the resilience and forward momentum of a people rebuilding their culture. The Royal Palace and Silver Pagoda are among the most beautiful royal complexes in Asia, while the Tuol Sleng Genocide Museum and the Killing Fields of Choeung Ek demand an honest confrontation with recent history that is among the most important travel experiences available. The city\'s food scene — amok fish curry, nom banh chok noodles, fresh river prawns on the Tonle Sap riverfront — is growing rapidly, and the energy of a young, hopeful population is palpable.' },
    { name: 'Guadalajara',     country: 'Mexico',          slug: 'guadalajara',       description: 'Guadalajara is the birthplace of everything most essentially Mexican: mariachi music was born in the surrounding state of Jalisco, tequila is produced in the town bearing its name just to the west, and the charreada — the Mexican rodeo tradition — was codified here. Mexico\'s second city is a place of grand colonial plazas, the extraordinary murals of José Clemente Orozco in the Hospicio Cabañas (a UNESCO World Heritage Site), and a culinary tradition centred on birria — the slow-braised goat stew that has become a global food phenomenon. The nearby villages of Tlaquepaque and Tonalá are two of Mexico\'s finest craft and artisan markets, making Guadalajara one of the country\'s most culturally rich destinations.' },
    { name: 'Krakow',          country: 'Poland',          slug: 'krakow',            description: 'Kraków is one of Europe\'s great medieval cities — Poland\'s royal capital for five centuries and the only major Polish city to survive the Second World War largely intact, preserving one of Europe\'s finest collections of Gothic, Renaissance, and Baroque architecture. The Rynek Główny, the Main Market Square, is the largest medieval square in Europe and the heart of a city that feels genuinely alive rather than preserved. The Wawel Castle and Cathedral, the Jewish Quarter of Kazimierz, and the sobering proximity of Auschwitz-Birkenau — which must be understood on any visit — make Kraków one of the most historically important and emotionally complex destinations in Europe.' },
    { name: 'Dakar',           country: 'Senegal',         slug: 'dakar',             description: 'Dakar is the westernmost point of continental Africa — a vibrant, wind-swept Atlantic peninsula that is one of West Africa\'s most dynamic cultural capitals. Senegal has one of Africa\'s most stable democracies and a proud cultural tradition: the music of Youssou N\'Dour has made Senegalese mbalax world famous, and the art and design scene of Dakar is among Africa\'s most innovative, showcased at the biennial Dak\'Art festival. The cuisine is extraordinary — thiéboudienne, the national dish of fish and rice cooked in tomato, was recognised by UNESCO as Intangible Cultural Heritage — and the beaches, the Île de Gorée slave house, and the Grand Mosque of Touba make Dakar a destination of deep historical and cultural resonance.' },
    { name: 'Hoi An',          country: 'Vietnam',         slug: 'hoi-an',            description: 'Hoi An is Vietnam\'s most perfectly preserved ancient trading town — a UNESCO World Heritage Site on the Thu Bon River whose Chinese merchant houses, Japanese covered bridge, French colonial shopfronts, and Vietnamese tube houses reflect the extraordinary mix of cultures that traded through its port from the 15th to the 19th century. At night, the town glows with the light of hundreds of silk lanterns reflected in the river, and the streets fill with visitors drawn to the phenomenal food — white rose dumplings, cao lau noodles, banh mi — that is considered by many chefs the finest in Vietnam. The tailors of Hoi An are legendary: bespoke clothing made to measure within 24 hours has been a tradition here for decades.' },
    { name: 'Amman',           country: 'Jordan',          slug: 'amman',             description: 'Amman is one of the Middle East\'s most liveable and welcoming capitals — a modern Arab city of great warmth and remarkable cuisine built across seven (now 19) hills in the Jordanian highlands. The city\'s Roman Theatre, one of the best-preserved in the region, and the Citadel\'s temple of Hercules overlook a growing metropolis whose café culture, gallery scene, and food have made it a regional hub for creativity and cuisine. Jordan\'s safety and exceptional hospitality culture make Amman the ideal base for visits to Petra, Wadi Rum\'s Mars-like desert, the Dead Sea, and the ancient Decapolis cities, and the mansaf and falafel of Rainbow Street are among the great pleasures of a Jordan visit.' },
    { name: 'Medina',          country: 'Saudi Arabia',    slug: 'medina',            description: 'Medina is Islam\'s second holiest city — the city to which the Prophet Muhammad migrated from Mecca in 622 CE, the Hijra that marks the beginning of the Islamic calendar. The Prophet\'s Mosque, Al-Masjid an-Nabawi, was built by Muhammad himself and contains his tomb, making it one of the most visited and revered sacred sites in the world. The city receives millions of Muslim pilgrims annually, many combining the visit with the Hajj or Umrah pilgrimage to nearby Mecca, and its atmosphere of devotion, hospitality, and spiritual weight is profound for all who visit with the appropriate respect and intention.' },
    { name: 'Tulum',           country: 'Mexico',          slug: 'tulum',             description: 'Tulum is the Yucatán Peninsula\'s most iconic destination — a place where ancient Mayan ruins perch dramatically on Caribbean cliffs above turquoise water, and where cenotes (sacred limestone sinkholes filled with crystal-clear groundwater) punctuate a jungle of extraordinary ecological diversity. The site was one of the last cities built and occupied by the Maya, and its coastal location made it a major trading port for jade and turquoise. The town itself has developed from a backpacker hideout into a destination for eco-luxury travel, with thatched-roof beach clubs, yoga retreats, and farm-to-table restaurants that have made it one of the most talked-about places in the Americas.' },
    { name: 'Siem Reap',       country: 'Cambodia',        slug: 'siem-reap',         description: 'Siem Reap is the gateway to Angkor — the largest religious monument complex on earth and one of humanity\'s greatest architectural achievements. The Khmer Empire built these temples between the 9th and 15th centuries, and the scale of Angkor Wat, the forest-engulfed faces of Bayon, and the tree-root-embraced ruins of Ta Prohm are genuinely overwhelming in person. Siem Reap itself has grown from a small market town into a vibrant destination with excellent food, the night markets of Pub Street, silk weaving workshops, and the Cambodian Cultural Village, all while retaining the warm, quiet charm of a Cambodian provincial city that makes it one of Southeast Asia\'s most loveable bases.' },
    { name: 'Plovdiv',         country: 'Bulgaria',        slug: 'plovdiv',           description: 'Plovdiv is one of Europe\'s oldest continuously inhabited cities — settled for over 8,000 years and built across seven hills in the Thracian plain of Bulgaria — yet it remains one of the continent\'s least-visited treasures. The Old Town\'s National Revival architecture, with its colour-washed merchant houses cantilevering dramatically over cobblestoned lanes, is among the most beautiful historic districts in the Balkans. The Roman amphitheatre in the city centre still hosts concerts and performances, and Plovdiv\'s designation as a 2019 European Capital of Culture brought global attention to a thriving arts and café scene that has made it one of Eastern Europe\'s most exciting emerging destinations.' },
    { name: 'Essaouira',       country: 'Morocco',         slug: 'essaouira',         description: 'Essaouira is Morocco\'s most atmospheric Atlantic port — a windswept, blue-and-white medina city of ramparts, fishing boats, and the haunting Gnawa music that drifts from every doorway. The constant Atlantic wind (Essaouira means "well-designed" in Berber, a nod to the fortifications) makes it a world-class kitesurfing and windsurfing destination, but the city\'s real draw is its melancholy beauty and creative energy. Jimi Hendrix famously visited in the 1960s and the town has drawn artists, musicians, and writers ever since; the argan oil produced in the surrounding forests, the freshly grilled sardines of the port, and the thuya wood craftsmen of the medina give it a sensory richness that is entirely its own.' },
    { name: 'Ghent',           country: 'Belgium',         slug: 'ghent',             description: 'Ghent is Belgium\'s most underrated city — a medieval canal city that rivals Bruges in architectural beauty but surpasses it in authentic, lived-in energy thanks to its large student population and thriving creative scene. The three towers of Sint-Baaf\'s Cathedral, Sint-Niklaaskerk, and the Belfort dominate a skyline above the Graslei quay that is arguably the most beautiful in the Low Countries. Sint-Baaf\'s Cathedral houses the Van Eyck brothers\' Ghent Altarpiece — considered by many art historians the most important painting in the Western world — and the city\'s craft beer culture, Thursday vegetarian market tradition, and the street art of the Werregarenstraat give it a progressive, creative character that makes it one of Europe\'s most rewarding short breaks.' },
    { name: 'Valletta',        country: 'Malta',           slug: 'valletta',          description: 'Valletta is Europe\'s smallest capital city — a Baroque fortified city-state built on a narrow peninsula between two of the Mediterranean\'s finest natural harbours by the Knights of St John in the 16th century. Every street in Valletta is a monument: the Co-Cathedral of St John contains Caravaggio\'s largest surviving painting, the Upper Barrakka Gardens offer the most dramatic harbour view in the Mediterranean, and the Grand Harbour itself is one of the great natural spectacles of the sea. Malta\'s unique history — Phoenician, Roman, Arab, Norman, Aragonese, Ottoman-besieged, French, British — has produced a culture, a language, and a cuisine (rabbit stew, pastizzi, ftira bread) unlike anywhere else in Europe.' },
    { name: 'Zanzibar',        country: 'Tanzania',        slug: 'zanzibar',          description: 'Zanzibar is the Indian Ocean\'s most evocative island — a spice-scented archipelago off the coast of Tanzania whose Stone Town is a UNESCO World Heritage Site reflecting centuries of Arab, Persian, Indian, and Swahili culture woven into a labyrinth of carved doorways, coral-stone mosques, and narrow lanes perfumed with cloves and cardamom. The island was the epicentre of the East African spice and slave trade for centuries, and its complex history is as compelling as its extraordinary beaches — Nungwi and Kendwa in the north, Paje in the east — which offer some of the finest white-sand swimming in Africa. Dhow sailing trips, snorkelling in marine parks, and the street food of Forodhani Gardens night market make Zanzibar one of the world\'s most complete island destinations.' },
    { name: 'Jaipur',          country: 'India',           slug: 'jaipur',            description: 'Jaipur is the Pink City of Rajasthan — a city painted in terracotta pink to welcome the Prince of Wales in 1876 and never changed back, giving it the most distinctive streetscape in India. The Amber Fort, rising above a lake on a desert ridge outside the city, is one of the subcontinent\'s finest examples of Rajput military architecture, and the City Palace, Hawa Mahal (Palace of Winds), and Jantar Mantar astronomical observatory fill the historic centre with extraordinary monuments. Jaipur is also one of India\'s great bazaar cities: the lanes of the old city are filled with block-print fabrics, blue pottery, gemstones, leather shoes, and silver jewellery, making it one of the finest shopping destinations in South Asia.' },
    { name: 'Helsinki',        country: 'Finland',         slug: 'helsinki',          description: 'Helsinki is the Baltic Sea\'s most elegant and thoughtfully designed capital — a city of neoclassical Senate Square, Art Nouveau neighbourhoods, and the quiet granite islands of the archipelago that give it a relationship with water as defining as Amsterdam or Stockholm. Finland\'s design culture is among the world\'s most celebrated — Marimekko, Iittala, and Aalto furniture are household names — and the Design Museum and Design District of Helsinki are essential visits. The city\'s sauna culture, the smoke sauna on Löyly\'s waterfront, the Esplanadi park market, and the reindeer and cloudberry dishes of Nordic cuisine give Helsinki a quiet, confident character that rewards visitors who take the time to understand it.' },
  ];

  // Deduplicate slugs before upserting
  const seen = new Set();
  const uniqueDestinations = destinationData.filter(d => {
    if (seen.has(d.slug)) return false;
    seen.add(d.slug);
    return true;
  });

  const destinations = {};
  for (const d of uniqueDestinations) {
    destinations[d.slug] = await prisma.destination.upsert({
      where: { slug: d.slug },
      update: { description: d.description },
      create: d,
    });
  }

  const d = destinations; // shorthand

  // ─── Places (100) ─────────────────────────────────────────────────────────
  const placesData = [
    // New York
    { name: 'Central Park',                    slug: 'central-park',                  dest: 'new-york',          cats: [cat.activity, cat.nature],                  address: 'Central Park, New York, NY',               lat: 40.7851,  lng: -73.9683, price: 'FREE' },
    { name: "Katz's Delicatessen",             slug: 'katzs-delicatessen',            dest: 'new-york',          cats: [cat.food],                                  address: '205 E Houston St, New York, NY',            lat: 40.7223,  lng: -73.9873, price: 'MODERATE' },
    { name: 'The Metropolitan Museum of Art',  slug: 'the-met',                       dest: 'new-york',          cats: [cat.attraction, cat.activity],               address: '1000 5th Ave, New York, NY',                lat: 40.7794,  lng: -73.9632, price: 'MODERATE' },
    { name: 'Brooklyn Bridge',                 slug: 'brooklyn-bridge',               dest: 'new-york',          cats: [cat.attraction, cat.activity, cat.nature],   address: 'Brooklyn Bridge, New York, NY',             lat: 40.7061,  lng: -73.9969, price: 'FREE' },
    { name: 'Employees Only',                  slug: 'employees-only',                dest: 'new-york',          cats: [cat.nightlife, cat.food],                    address: '510 Hudson St, New York, NY',               lat: 40.7335,  lng: -74.0050, price: 'EXPENSIVE' },
    // Tokyo
    { name: 'Senso-ji Temple',                 slug: 'senso-ji',                      dest: 'tokyo',             cats: [cat.attraction, cat.activity],               address: '2-3-1 Asakusa, Taito City, Tokyo',          lat: 35.7148,  lng: 139.7967, price: 'FREE' },
    { name: 'Tsukiji Outer Market',            slug: 'tsukiji-outer-market',          dest: 'tokyo',             cats: [cat.food, cat.shopping],                    address: '4-16-2 Tsukiji, Chuo City, Tokyo',          lat: 35.6654,  lng: 139.7707, price: 'BUDGET' },
    { name: 'Shibuya Crossing',                slug: 'shibuya-crossing',              dest: 'tokyo',             cats: [cat.attraction],                             address: 'Shibuya, Tokyo',                            lat: 35.6595,  lng: 139.7004, price: 'FREE' },
    { name: 'Shinjuku Golden Gai',             slug: 'shinjuku-golden-gai',           dest: 'tokyo',             cats: [cat.nightlife, cat.food],                    address: 'Kabukicho, Shinjuku City, Tokyo',           lat: 35.6938,  lng: 139.7036, price: 'MODERATE' },
    { name: 'Takeshita Street',                slug: 'takeshita-street',              dest: 'tokyo',             cats: [cat.shopping, cat.food],                    address: 'Takeshita St, Harajuku, Tokyo',             lat: 35.6703,  lng: 139.7027, price: 'BUDGET' },
    // Paris
    { name: 'Eiffel Tower',                    slug: 'eiffel-tower',                  dest: 'paris',             cats: [cat.attraction],                             address: 'Champ de Mars, Paris',                      lat: 48.8584,  lng: 2.2945,   price: 'MODERATE' },
    { name: 'Louvre Museum',                   slug: 'louvre-museum',                 dest: 'paris',             cats: [cat.attraction, cat.activity],               address: 'Rue de Rivoli, 75001 Paris',                lat: 48.8606,  lng: 2.3376,   price: 'MODERATE' },
    { name: 'Septime',                         slug: 'septime',                       dest: 'paris',             cats: [cat.food],                                  address: '80 Rue de Charonne, 75011 Paris',           lat: 48.8532,  lng: 2.3797,   price: 'EXPENSIVE' },
    { name: 'Montmartre',                      slug: 'montmartre',                    dest: 'paris',             cats: [cat.attraction, cat.activity, cat.nature],   address: 'Montmartre, Paris',                         lat: 48.8867,  lng: 2.3431,   price: 'FREE' },
    // Mexico City
    { name: 'Teotihuacán',                     slug: 'teotihuacan',                   dest: 'mexico-city',       cats: [cat.attraction, cat.activity],               address: 'San Juan Teotihuacán, Mexico',              lat: 19.6925,  lng: -98.8438, price: 'BUDGET' },
    { name: 'Mercado Roma',                    slug: 'mercado-roma',                  dest: 'mexico-city',       cats: [cat.food, cat.shopping],                    address: 'Querétaro 225, Roma Nte., Mexico City',     lat: 19.4186,  lng: -99.1607, price: 'BUDGET' },
    { name: 'Chapultepec Park',                slug: 'chapultepec-park',              dest: 'mexico-city',       cats: [cat.nature, cat.activity, cat.attraction],   address: 'Miguel Hidalgo, Mexico City',               lat: 19.4204,  lng: -99.1944, price: 'FREE' },
    { name: 'La Ópera Bar',                    slug: 'la-opera-bar',                  dest: 'mexico-city',       cats: [cat.nightlife, cat.food, cat.attraction],    address: '5 de Mayo 10, Centro, Mexico City',         lat: 19.4353,  lng: -99.1386, price: 'MODERATE' },
    // London
    { name: 'Tower of London',                 slug: 'tower-of-london',               dest: 'london',            cats: [cat.attraction],                             address: 'Tower Hill, London EC3N 4AB',               lat: 51.5081,  lng: -0.0759,  price: 'EXPENSIVE' },
    { name: 'Borough Market',                  slug: 'borough-market',                dest: 'london',            cats: [cat.food, cat.shopping],                    address: '8 Southwark St, London SE1 1TL',            lat: 51.5055,  lng: -0.0910,  price: 'BUDGET' },
    { name: 'Hyde Park',                       slug: 'hyde-park',                     dest: 'london',            cats: [cat.nature, cat.activity],                  address: 'Hyde Park, London',                         lat: 51.5073,  lng: -0.1657,  price: 'FREE' },
    { name: 'Sketch London',                   slug: 'sketch-london',                 dest: 'london',            cats: [cat.food, cat.nightlife],                   address: '9 Conduit St, London W1S 2XG',              lat: 51.5131,  lng: -0.1427,  price: 'EXPENSIVE' },
    // Barcelona
    { name: 'Sagrada Família',                 slug: 'sagrada-familia',               dest: 'barcelona',         cats: [cat.attraction],                             address: 'Carrer de Mallorca, 401, Barcelona',        lat: 41.4036,  lng: 2.1744,   price: 'MODERATE' },
    { name: 'La Boqueria Market',              slug: 'la-boqueria',                   dest: 'barcelona',         cats: [cat.food, cat.shopping, cat.attraction],     address: 'La Rambla, 91, Barcelona',                  lat: 41.3816,  lng: 2.1718,   price: 'FREE' },
    { name: 'Park Güell',                      slug: 'park-guell',                    dest: 'barcelona',         cats: [cat.attraction, cat.nature],                address: '08024 Barcelona',                           lat: 41.4145,  lng: 2.1527,   price: 'MODERATE' },
    { name: 'El Xampanyet',                    slug: 'el-xampanyet',                  dest: 'barcelona',         cats: [cat.food, cat.nightlife],                   address: "C/ de Montcada, 22, Barcelona",             lat: 41.3839,  lng: 2.1813,   price: 'BUDGET' },
    // Rome
    { name: 'Colosseum',                       slug: 'colosseum',                     dest: 'rome',              cats: [cat.attraction],                             address: 'Piazza del Colosseo, 1, Rome',              lat: 41.8902,  lng: 12.4922,  price: 'MODERATE' },
    { name: 'Trastevere Neighbourhood',        slug: 'trastevere',                    dest: 'rome',              cats: [cat.food, cat.nightlife, cat.attraction],    address: 'Trastevere, Rome',                          lat: 41.8896,  lng: 12.4686,  price: 'FREE' },
    { name: 'Gelato di San Crispino',          slug: 'gelato-san-crispino',           dest: 'rome',              cats: [cat.food],                                  address: 'Via della Panetteria, 42, Rome',            lat: 41.9006,  lng: 12.4838,  price: 'BUDGET' },
    // Bangkok
    { name: 'Wat Pho',                         slug: 'wat-pho',                       dest: 'bangkok',           cats: [cat.attraction],                             address: '2 Sanam Chai Rd, Bangkok',                  lat: 13.7465,  lng: 100.4930, price: 'BUDGET' },
    { name: 'Chatuchak Weekend Market',        slug: 'chatuchak-market',              dest: 'bangkok',           cats: [cat.shopping, cat.food],                    address: 'Kamphaeng Phet 2 Rd, Bangkok',              lat: 13.7999,  lng: 100.5500, price: 'FREE' },
    { name: 'Thipsamai Pad Thai',              slug: 'thipsamai-pad-thai',            dest: 'bangkok',           cats: [cat.food],                                  address: '313 Maha Chai Rd, Bangkok',                 lat: 13.7535,  lng: 100.5014, price: 'BUDGET' },
    // Sydney
    { name: 'Sydney Opera House',              slug: 'sydney-opera-house',            dest: 'sydney',            cats: [cat.attraction],                             address: 'Bennelong Point, Sydney NSW 2000',          lat: -33.8568, lng: 151.2153, price: 'FREE' },
    { name: 'Bondi Beach',                     slug: 'bondi-beach',                   dest: 'sydney',            cats: [cat.nature, cat.activity],                  address: 'Bondi Beach NSW 2026',                      lat: -33.8915, lng: 151.2767, price: 'FREE' },
    { name: 'Quay Restaurant',                 slug: 'quay-restaurant',               dest: 'sydney',            cats: [cat.food],                                  address: 'Upper Level, Overseas Passenger Terminal, Sydney', lat: -33.8598, lng: 151.2099, price: 'EXPENSIVE' },
    // Cape Town
    { name: 'Table Mountain',                  slug: 'table-mountain',                dest: 'cape-town',         cats: [cat.nature, cat.activity, cat.attraction],   address: 'Table Mountain, Cape Town',                 lat: -33.9628, lng: 18.4098,  price: 'MODERATE' },
    { name: 'V&A Waterfront',                  slug: 'va-waterfront',                 dest: 'cape-town',         cats: [cat.shopping, cat.food, cat.nightlife],      address: 'V&A Waterfront, Cape Town',                 lat: -33.9042, lng: 18.4196,  price: 'FREE' },
    { name: 'Boulders Beach Penguins',         slug: 'boulders-beach',                dest: 'cape-town',         cats: [cat.nature, cat.activity],                  address: 'Boulders Beach, Simon\'s Town',              lat: -34.1978, lng: 18.4511,  price: 'BUDGET' },
    // Dubai
    { name: 'Burj Khalifa',                    slug: 'burj-khalifa',                  dest: 'dubai',             cats: [cat.attraction],                             address: '1 Sheikh Mohammed bin Rashid Blvd, Dubai',  lat: 25.1972,  lng: 55.2744,  price: 'EXPENSIVE' },
    { name: 'Dubai Spice Souk',                slug: 'dubai-spice-souk',              dest: 'dubai',             cats: [cat.shopping, cat.attraction],               address: 'Al Ras, Deira, Dubai',                      lat: 25.2637,  lng: 55.2988,  price: 'FREE' },
    { name: 'Al Fanar Restaurant',             slug: 'al-fanar-restaurant',           dest: 'dubai',             cats: [cat.food],                                  address: 'Festival City Mall, Dubai',                 lat: 25.2302,  lng: 55.3529,  price: 'MODERATE' },
    // Istanbul
    { name: 'Hagia Sophia',                    slug: 'hagia-sophia',                  dest: 'istanbul',          cats: [cat.attraction],                             address: 'Sultan Ahmet, Fatih, Istanbul',             lat: 41.0086,  lng: 28.9802,  price: 'FREE' },
    { name: 'Grand Bazaar',                    slug: 'grand-bazaar',                  dest: 'istanbul',          cats: [cat.shopping, cat.attraction],               address: 'Kapalıçarşı, Istanbul',                     lat: 41.0108,  lng: 28.9680,  price: 'FREE' },
    { name: 'Mikla Restaurant',                slug: 'mikla-restaurant',              dest: 'istanbul',          cats: [cat.food, cat.nightlife],                   address: 'Meşrutiyet Cd. No:15, Beyoğlu, Istanbul',  lat: 41.0338,  lng: 28.9772,  price: 'EXPENSIVE' },
    // Amsterdam
    { name: 'Rijksmuseum',                     slug: 'rijksmuseum',                   dest: 'amsterdam',         cats: [cat.attraction, cat.activity],               address: 'Museumstraat 1, 1071 XX Amsterdam',         lat: 52.3600,  lng: 4.8852,   price: 'MODERATE' },
    { name: 'Jordaan Canal Stroll',            slug: 'jordaan-canals',                dest: 'amsterdam',         cats: [cat.nature, cat.activity, cat.attraction],   address: 'Jordaan, Amsterdam',                        lat: 52.3751,  lng: 4.8814,   price: 'FREE' },
    { name: "Brouwerij 't IJ",                slug: 'brouwerij-ij',                  dest: 'amsterdam',         cats: [cat.food, cat.nightlife],                   address: 'Funenkade 7, 1018 AL Amsterdam',            lat: 52.3663,  lng: 4.9200,   price: 'BUDGET' },
    // Singapore
    { name: 'Gardens by the Bay',              slug: 'gardens-by-the-bay',            dest: 'singapore',         cats: [cat.nature, cat.attraction, cat.activity],   address: '18 Marina Gardens Dr, Singapore 018953',   lat: 1.2816,   lng: 103.8636, price: 'MODERATE' },
    { name: 'Maxwell Food Centre',             slug: 'maxwell-food-centre',           dest: 'singapore',         cats: [cat.food],                                  address: '1 Kadayanallur St, Singapore 069184',       lat: 1.2802,   lng: 103.8447, price: 'BUDGET' },
    { name: 'Clarke Quay',                     slug: 'clarke-quay',                   dest: 'singapore',         cats: [cat.nightlife, cat.food],                   address: '3E River Valley Rd, Singapore 179024',     lat: 1.2906,   lng: 103.8467, price: 'MODERATE' },
    // Buenos Aires
    { name: 'La Boca Neighbourhood',           slug: 'la-boca',                       dest: 'buenos-aires',      cats: [cat.attraction, cat.activity],               address: 'La Boca, Buenos Aires',                     lat: -34.6345, lng: -58.3631, price: 'FREE' },
    { name: 'Café Tortoni',                    slug: 'cafe-tortoni',                  dest: 'buenos-aires',      cats: [cat.food, cat.attraction],                  address: 'Av. de Mayo 825, Buenos Aires',             lat: -34.6088, lng: -58.3748, price: 'BUDGET' },
    { name: 'Don Julio Parrilla',              slug: 'don-julio-parrilla',            dest: 'buenos-aires',      cats: [cat.food],                                  address: 'Guatemala 4699, Buenos Aires',              lat: -34.5875, lng: -58.4254, price: 'EXPENSIVE' },
    // Bali
    { name: 'Ubud Sacred Monkey Forest',       slug: 'ubud-monkey-forest',            dest: 'bali',              cats: [cat.nature, cat.attraction],                address: 'Jl. Monkey Forest, Ubud, Bali',             lat: -8.5188,  lng: 115.2620, price: 'BUDGET' },
    { name: 'Tanah Lot Temple',                slug: 'tanah-lot',                     dest: 'bali',              cats: [cat.attraction, cat.nature],                address: 'Beraban, Kediri, Tabanan, Bali',            lat: -8.6215,  lng: 115.0866, price: 'BUDGET' },
    { name: 'Locavore Restaurant',             slug: 'locavore-bali',                 dest: 'bali',              cats: [cat.food],                                  address: 'Jl. Dewi Sita, Ubud, Bali',                lat: -8.5073,  lng: 115.2632, price: 'EXPENSIVE' },
    // Marrakech
    { name: 'Djemaa el-Fna',                  slug: 'djemaa-el-fna',                 dest: 'marrakech',         cats: [cat.attraction, cat.food, cat.nightlife],    address: 'Jamaa el Fna, Marrakech',                  lat: 31.6259,  lng: -7.9891,  price: 'FREE' },
    { name: 'Bahia Palace',                    slug: 'bahia-palace',                  dest: 'marrakech',         cats: [cat.attraction],                             address: 'Rue Riad Zitoun el Jadid, Marrakech',      lat: 31.6212,  lng: -7.9836,  price: 'BUDGET' },
    { name: 'Souk Semmarine',                  slug: 'souk-semmarine',                dest: 'marrakech',         cats: [cat.shopping, cat.attraction],               address: 'Souk Semmarine, Marrakech Medina',          lat: 31.6310,  lng: -7.9869,  price: 'FREE' },
    // Kyoto
    { name: 'Arashiyama Bamboo Grove',         slug: 'arashiyama-bamboo',             dest: 'kyoto',             cats: [cat.nature, cat.attraction],                address: 'Sagaogurayama Tabuchiyamacho, Kyoto',       lat: 35.0094,  lng: 135.6728, price: 'FREE' },
    { name: 'Fushimi Inari Shrine',            slug: 'fushimi-inari',                 dest: 'kyoto',             cats: [cat.attraction, cat.activity],               address: '68 Fukakusa Yabunouchicho, Fushimi, Kyoto', lat: 34.9671,  lng: 135.7727, price: 'FREE' },
    { name: 'Nishiki Market',                  slug: 'nishiki-market',                dest: 'kyoto',             cats: [cat.food, cat.shopping],                    address: 'Nishiki Market, Nakagyo Ward, Kyoto',       lat: 35.0048,  lng: 135.7641, price: 'FREE' },
    // Rio de Janeiro
    { name: 'Christ the Redeemer',             slug: 'christ-the-redeemer',           dest: 'rio-de-janeiro',    cats: [cat.attraction],                             address: 'Parque Nacional da Tijuca, Rio de Janeiro', lat: -22.9519, lng: -43.2105, price: 'MODERATE' },
    { name: 'Ipanema Beach',                   slug: 'ipanema-beach',                 dest: 'rio-de-janeiro',    cats: [cat.nature, cat.activity],                  address: 'Ipanema, Rio de Janeiro',                   lat: -22.9877, lng: -43.2020, price: 'FREE' },
    { name: 'Confeitaria Colombo',             slug: 'confeitaria-colombo',           dest: 'rio-de-janeiro',    cats: [cat.food, cat.attraction],                  address: 'R. Gonçalves Dias 32, Centro, Rio',         lat: -22.9057, lng: -43.1775, price: 'MODERATE' },
    // Seoul
    { name: 'Gyeongbokgung Palace',            slug: 'gyeongbokgung',                 dest: 'seoul',             cats: [cat.attraction],                             address: '161 Sajik-ro, Jongno-gu, Seoul',            lat: 37.5796,  lng: 126.9770, price: 'BUDGET' },
    { name: 'Gwangjang Market',                slug: 'gwangjang-market',              dest: 'seoul',             cats: [cat.food, cat.shopping],                    address: '88 Changgyeonggung-ro, Jongno-gu, Seoul',  lat: 37.5698,  lng: 126.9992, price: 'BUDGET' },
    { name: 'Hongdae District',                slug: 'hongdae',                       dest: 'seoul',             cats: [cat.nightlife, cat.shopping, cat.activity],  address: 'Hongdae, Mapo-gu, Seoul',                   lat: 37.5563,  lng: 126.9233, price: 'FREE' },
    // New Orleans
    { name: 'French Quarter',                  slug: 'french-quarter',                dest: 'new-orleans',       cats: [cat.attraction, cat.nightlife],              address: 'French Quarter, New Orleans, LA',           lat: 29.9584,  lng: -90.0644, price: 'FREE' },
    { name: 'Café Du Monde',                   slug: 'cafe-du-monde',                 dest: 'new-orleans',       cats: [cat.food, cat.attraction],                  address: '800 Decatur St, New Orleans, LA 70116',    lat: 29.9571,  lng: -90.0615, price: 'BUDGET' },
    { name: 'Preservation Hall',               slug: 'preservation-hall',             dest: 'new-orleans',       cats: [cat.nightlife, cat.attraction],              address: '726 St Peter St, New Orleans, LA 70116',   lat: 29.9584,  lng: -90.0660, price: 'BUDGET' },
    // Prague
    { name: 'Prague Castle',                   slug: 'prague-castle',                 dest: 'prague',            cats: [cat.attraction],                             address: 'Hradčany, 119 08 Prague',                   lat: 50.0909,  lng: 14.4009,  price: 'MODERATE' },
    { name: 'Old Town Square',                 slug: 'old-town-square-prague',        dest: 'prague',            cats: [cat.attraction, cat.activity],               address: 'Old Town Square, Prague',                   lat: 50.0875,  lng: 14.4213,  price: 'FREE' },
    { name: 'U Fleků Brewery',                 slug: 'u-fleku-brewery',               dest: 'prague',            cats: [cat.food, cat.nightlife, cat.attraction],    address: 'Křemencova 11, 110 00 Prague',              lat: 50.0800,  lng: 14.4175,  price: 'BUDGET' },
    // Lisbon
    { name: 'Belém Tower',                     slug: 'belem-tower',                   dest: 'lisbon',            cats: [cat.attraction],                             address: 'Av. Brasília, 1400-038 Lisbon',             lat: 38.6916,  lng: -9.2160,  price: 'BUDGET' },
    { name: 'Time Out Market',                 slug: 'timeout-market-lisbon',         dest: 'lisbon',            cats: [cat.food, cat.activity],                    address: 'Av. 24 de Julho 49, 1200-479 Lisbon',      lat: 38.7067,  lng: -9.1458,  price: 'BUDGET' },
    { name: 'LX Factory',                      slug: 'lx-factory',                    dest: 'lisbon',            cats: [cat.shopping, cat.food, cat.nightlife],      address: 'R. Rodrigues de Faria 103, Lisbon',         lat: 38.7035,  lng: -9.1790,  price: 'FREE' },
    // Florence
    { name: 'Uffizi Gallery',                  slug: 'uffizi-gallery',                dest: 'florence',          cats: [cat.attraction, cat.activity],               address: 'Piazzale degli Uffizi, 6, Florence',        lat: 43.7677,  lng: 11.2553,  price: 'EXPENSIVE' },
    { name: 'Mercato Centrale',                slug: 'mercato-centrale-florence',     dest: 'florence',          cats: [cat.food, cat.shopping],                    address: 'Piazza del Mercato Centrale, Florence',     lat: 43.7765,  lng: 11.2537,  price: 'FREE' },
    { name: 'Piazzale Michelangelo',           slug: 'piazzale-michelangelo',         dest: 'florence',          cats: [cat.attraction, cat.nature],                address: 'Piazzale Michelangelo, Florence',           lat: 43.7629,  lng: 11.2654,  price: 'FREE' },
    // Chicago
    { name: 'Millennium Park',                 slug: 'millennium-park',               dest: 'chicago',           cats: [cat.attraction, cat.nature, cat.activity],   address: '201 E Randolph St, Chicago, IL 60602',     lat: 41.8826,  lng: -87.6233, price: 'FREE' },
    { name: 'Lou Malnati\'s Pizzeria',         slug: 'lou-malnatis',                  dest: 'chicago',           cats: [cat.food],                                  address: '439 N Wells St, Chicago, IL 60654',        lat: 41.8905,  lng: -87.6341, price: 'BUDGET' },
    { name: 'Chicago Riverwalk',               slug: 'chicago-riverwalk',             dest: 'chicago',           cats: [cat.activity, cat.nature, cat.attraction],   address: 'Chicago Riverwalk, Chicago, IL',            lat: 41.8863,  lng: -87.6261, price: 'FREE' },
    // Budapest
    { name: 'Széchenyi Thermal Bath',          slug: 'szechenyi-baths',               dest: 'budapest',          cats: [cat.activity, cat.attraction],               address: 'Állatkerti krt. 9-11, Budapest',            lat: 47.5190,  lng: 19.0826,  price: 'MODERATE' },
    { name: 'Ruin Bars of the Jewish Quarter', slug: 'ruin-bars-budapest',            dest: 'budapest',          cats: [cat.nightlife, cat.attraction],              address: 'Kazinczy utca, Budapest VII',               lat: 47.4990,  lng: 19.0637,  price: 'BUDGET' },
    { name: 'Central Market Hall',             slug: 'central-market-hall-budapest',  dest: 'budapest',          cats: [cat.food, cat.shopping, cat.attraction],     address: 'Vámház krt. 1-3, Budapest',                lat: 47.4870,  lng: 19.0596,  price: 'FREE' },
    // Jaipur
    { name: 'Amber Fort',                      slug: 'amber-fort',                    dest: 'jaipur',            cats: [cat.attraction, cat.activity],               address: 'Devisinghpura, Amer, Jaipur',               lat: 26.9855,  lng: 75.8514,  price: 'MODERATE' },
    { name: 'Johari Bazaar',                   slug: 'johari-bazaar',                 dest: 'jaipur',            cats: [cat.shopping, cat.attraction],               address: 'Johari Bazaar, Jaipur',                     lat: 26.9161,  lng: 75.8209,  price: 'FREE' },
    // Queenstown
    { name: 'Skyline Gondola & Luge',          slug: 'skyline-gondola-queenstown',    dest: 'queenstown',        cats: [cat.activity, cat.attraction, cat.nature],   address: 'Brecon St, Queenstown 9300, NZ',            lat: -45.0263, lng: 168.6609, price: 'EXPENSIVE' },
    { name: 'Fergburger',                      slug: 'fergburger',                    dest: 'queenstown',        cats: [cat.food],                                  address: '42 Shotover St, Queenstown, NZ',            lat: -45.0305, lng: 168.6616, price: 'BUDGET' },
    // Tulum
    { name: 'Tulum Mayan Ruins',               slug: 'tulum-ruins',                   dest: 'tulum',             cats: [cat.attraction, cat.nature],                address: 'Tulum Ruins, Quintana Roo, Mexico',         lat: 20.2141,  lng: -87.4286, price: 'BUDGET' },
    { name: 'Gran Cenote',                     slug: 'gran-cenote',                   dest: 'tulum',             cats: [cat.nature, cat.activity],                  address: 'Carr. Tulum-Cobá Km 3, Tulum, Mexico',     lat: 20.2399,  lng: -87.4636, price: 'BUDGET' },
    // Zanzibar
    { name: 'Stone Town',                      slug: 'stone-town',                    dest: 'zanzibar',          cats: [cat.attraction, cat.shopping],               address: 'Stone Town, Zanzibar City, Tanzania',       lat: -6.1628,  lng: 39.1892,  price: 'FREE' },
    { name: 'Nungwi Beach',                    slug: 'nungwi-beach',                  dest: 'zanzibar',          cats: [cat.nature, cat.activity],                  address: 'Nungwi, Zanzibar North A, Tanzania',        lat: -5.7238,  lng: 39.2975,  price: 'FREE' },
  ];

  for (const p of placesData) {
    if (!d[p.dest]) continue;
    const place = await prisma.place.upsert({
      where: { slug: p.slug },
      update: {},
      create: {
        name: p.name,
        slug: p.slug,
        address: p.address,
        latitude: p.lat,
        longitude: p.lng,
        priceRange: p.price,
        destinationId: d[p.dest].id,
      },
    });
    await assignCategories(place.id, p.cats);
  }

  // ─── Featured Destinations ────────────────────────────────────────────────
  // Curated list shown on the homepage. position is 1-based display order.
  // Add/remove slugs here; re-running is safe (upsert).
  const featuredSlugs = [
    'paris', 'tokyo', 'new-york', 'barcelona', 'rome',
    'amsterdam', 'london', 'lisbon', 'istanbul', 'bali',
  ];
  for (let i = 0; i < featuredSlugs.length; i++) {
    const dest = await prisma.destination.findUnique({ where: { slug: featuredSlugs[i] } });
    if (!dest) { console.warn(`Featured seed: slug "${featuredSlugs[i]}" not found — skipping`); continue; }
    await prisma.featuredDestination.upsert({
      where:  { destinationId: dest.id },
      update: { position: i + 1 },
      create: { destinationId: dest.id, position: i + 1 },
    });
  }
  console.log(`Featured destinations seeded: ${featuredSlugs.length} entries`);

  const destCount = await prisma.destination.count();
  const placeCount = await prisma.place.count();
  console.log(`Seed complete: ${destCount} destinations, ${placeCount} places`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
